### PR TITLE
Update in order to close vulnerabilities

### PR DESCRIPTION
**Pull request by ActionAnalytics**

### CODE REVIEW

**Comment by ActionAnalytics** [comment]
We haven't tested this yet but our intention was to try it with assistance from the lab.  We ran locally with these settings but we still need to try it in OpenShift.

**Comment by cvarjao** [comment]
@ActionAnalytics, does this requires a new `jenkins-slave-bddstack` with recent chrome/firefox by chance?

**Comment by ActionAnalytics** [comment]
Used docker-registry.default.svc:5000/bcgov/jenkins-slave-bddstack:v1-stable and got green builds.

**Review by ShellyXueHan — APPROVED** [review]
Thank you for contribution!

**Pull request merged**
